# Generated by Django 4.1.7 on 2023-03-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('area', models.IntegerField()),
                ('description', models.TextField()),
                ('credit', models.BooleanField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='obra_images')),
            ],
        ),
    ]
